version: '3'

tasks:
  build-release-candidate:
    vars:
      VERSION:
        sh: cat Versionfile
      TIMESTAMP:
        sh: date +"%y%m%d%H%M"
      BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
    cmds:
      - cmd: git tag {{.VERSION}}-rc-{{.TIMESTAMP}}
      - cmd: git push origin {{.BRANCH}} --tags
      - cmd: echo 'A build+deploy has been triggered here https://github.com/equationscp/equationscp/actions.'
  build-release:
    vars:
      VERSION:
        sh: cat version
    cmds:
      - git tag {{.VERSION}}
      - cmd: git push origin main --tags
      - cmd: echo 'A build+deploy has been triggered here https://github.com/equationscp/equationscp/actions.'